server:
  port: 9090
spring:
  application:
    name: api-gateway
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    urls:
      - name: API Gateway
        url: /v3/api-docs
      - name: Auth Service
        url: http://auth-service:9092/v3/api-docs
      - name: Ledger Service
        url: http://ledger-service:9091/v3/api-docs
      - name: HR Service
        url: http://hr-service:9094/v3/api-docs
      - name: Student Service
        url: http://student-service:9095/v3/api-docs
      - name: Reporting Service
        url: http://reporting-service:9096/v3/api-docs

# Base URLs for upstream services (override via env in Docker)
services:
  auth: ${AUTH_BASE_URL:http://localhost:9092}
  ledger: ${LEDGER_BASE_URL:http://localhost:9091}
  hr: ${HR_BASE_URL:http://localhost:9094}
  student: ${STUDENT_BASE_URL:http://localhost:9095}
  reporting: ${REPORTING_BASE_URL:http://localhost:9096}
