server:
  port: 9095
spring:
  application:
    name: student-service
  datasource:
    url: jdbc:postgresql://localhost:5432/sncrwanda?currentSchema=students
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.default_schema: students

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
