server:
  port: 9096
spring:
  application:
    name: reporting-service
  datasource:
    url: jdbc:postgresql://postgres:5432/sncrwanda?currentSchema=reporting
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
