server:
  port: 8082
spring:
  application:
    name: ledger-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    # Use the Docker service name for Postgres; database created by compose as 'sncrwanda'
    url: jdbc:postgresql://localhost:5432/sncrwanda?currentSchema=ledger
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.default_schema: ledger

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
