server:
  port: 9091
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/sncrwanda?currentSchema=ledger
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
