services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sncrwanda
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-schemas.sql:/docker-entrypoint-initdb.d/init-schemas.sql:ro

  ledger-service:
    image: ledger-service:latest
    build:
      context: ../ledger-service
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    depends_on:
      - postgres

  auth-service:
    image: auth-service:latest
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
    environment:
      - MAIL_HOST=${MAIL_HOST:-}
      - MAIL_PORT=${MAIL_PORT:-}
      - MAIL_USERNAME=${MAIL_USERNAME:-}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-}
      - MAIL_SMTP_AUTH=${MAIL_SMTP_AUTH:-true}
      - MAIL_SMTP_STARTTLS=${MAIL_SMTP_STARTTLS:-true}
      - MAIL_FROM=${MAIL_FROM:-no-reply@sncrwanda.local}
      - APP_URL_BASE=${APP_URL_BASE:-http://localhost:5173}
    depends_on:
      - postgres

  api-gateway:
    image: api-gateway:latest
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - AUTH_BASE_URL=http://auth-service:9092
      - LEDGER_BASE_URL=http://ledger-service:9091
      - HR_BASE_URL=http://hr-service:9094
      - STUDENT_BASE_URL=http://student-service:9095
      - REPORTING_BASE_URL=http://reporting-service:9096
    depends_on:
      - auth-service
      - ledger-service

  hr-service:
    image: hr-service:latest
    build:
      context: ../hr-service
      dockerfile: Dockerfile
    ports:
      - "9094:9094"
    environment:
      - SERVER_PORT=9094
    depends_on:
      - postgres

  student-service:
    image: student-service:latest
    build:
      context: ../student-service
      dockerfile: Dockerfile
    ports:
      - "9095:9095"
    environment:
      - SERVER_PORT=9095
    depends_on:
      - postgres

  reporting-service:
    image: reporting-service:latest
    build:
      context: ../reporting-service
      dockerfile: Dockerfile
    ports:
      - "9096:9096"
    environment:
      - SERVER_PORT=9096
    depends_on:
      - postgres

volumes:
  pgdata: {}
