package org.sncrwanda.student.domain;
public enum Need { PHYSICAL, HEARING, SOCIAL_COMMUNICATION_AUTISM, MENTAL_EMOTIONAL_HEALTH, HEALTH_CONDITION, MOBILITY, VISUAL, SPEECH_LANGUAGE, LEARNING, OTHER }
