server:
  port: 9094
spring:
  application:
    name: hr-service
  datasource:
    # Use the Docker service name for Postgres; database created by compose as 'sncrwanda'
    url: jdbc:postgresql://localhost:5432/sncrwanda?currentSchema=hr
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.default_schema: hr

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
