server:
  port: 9092
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgres:5432/sncrwanda?currentSchema=auth
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  mail:
    host: ${MAIL_HOST:}
    port: ${MAIL_PORT:}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS:true}

# JWK set URI for JwtDecoder (container-resolvable default)
auth:
  jwt:
    jwk-set-uri: http://api-gateway:9090/.well-known/jwks.json

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  health:
    mail:
      enabled: false

app:
  url-base: ${APP_URL_BASE:http://localhost:5173}
  mail:
    from: ${MAIL_FROM:no-reply@sncrwanda.local}

# Toggle verbose request-body logging (default: false)
  logging:
    body:
      enabled: false
